name = "Agorism"
description = "Radical marketing."
keywords = "free markets"
image = "agorism.webp"
theme = "dark"
primary_color = "#fcba03"
text_align = "center"
gtag_id = ""
base_url = "https://agorism.org"

[[sections]]
title = "Agorist Fiction"
description = "Science Fiction and Fantasy"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "The Legend of Anarcho Claus"
description = "The Secret Story of Santa’s Rebel Son"
url = "https://notes.agorist.net/the_legend_of_anarcho_claus/"

[[sections]]
title = "Agorist Fact"
description = "Classic non-fiction"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "New Libertarian Manifesto by SEK3"
description = ""
url = ""
[[sections.items]]
title = "An Agorist Primer by SEK3"
description = ""
url = ""

[[sections]]
title = "Links"
description = "Other resources"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "SEK3's writings"
url = "https://www.sek3.net/"
[[sections.items]]
title = "SEK3's fanzines"
url = "https://www.sek3.org/"
[[sections.items]]
title = "Wikipedia"
url = "https://en.wikipedia.org/wiki/Agorism"
[[sections.items]]
title = "KoPubCo"
url = "https://kopubco.com/"
[[sections.items]]
title = "The Agorist Archives"
url = "https://archives.kopubco.com/"

[[sections]]
title = "Other good libraries for more reading"
description = "Without endorsement of anyone's content policy"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Free The People"
url = "https://freethepeople.org/library/"
[[sections.items]]
title = "Mises Institute"
url = "https://mises.org/library"
[[sections.items]]
title = "Center for a Stateless Society"
url = "https://c4ss.org/resources"
